name: 'Get Release'
description: 'Get release by tag name and set upload_url output if exists'
inputs:
  tag:
    description: 'release tag name'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
